set(_CATKIN_CURRENT_PACKAGE "slopeogm")
set(slopeogm_VERSION "0.0.0")
set(slopeogm_MAINTAINER "Jerry JI <jikaijin94@gmail.com>")
set(slopeogm_PACKAGE_FORMAT "2")
set(slopeogm_BUILD_DEPENDS "g++-static" "protobuf-dev" "python-sphinx" "message_generation" "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(slopeogm_BUILD_EXPORT_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(slopeogm_BUILDTOOL_DEPENDS "catkin")
set(slopeogm_BUILDTOOL_EXPORT_DEPENDS )
set(slopeogm_EXEC_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(slopeogm_RUN_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(slopeogm_TEST_DEPENDS )
set(slopeogm_DOC_DEPENDS )
set(slopeogm_URL_WEBSITE "")
set(slopeogm_URL_BUGTRACKER "")
set(slopeogm_URL_REPOSITORY "")
set(slopeogm_DEPRECATED "")