set(_CATKIN_CURRENT_PACKAGE "sensor_driver")
set(sensor_driver_VERSION "0.0.0")
set(sensor_driver_MAINTAINER "Jerry JI <jikaijin94@gmail.com>")
set(sensor_driver_PACKAGE_FORMAT "2")
set(sensor_driver_BUILD_DEPENDS "ivcommon" "sensor_driver_msgs" "geometry_msgs" "message_runtime" "nav_msgs" "rosbag" "roscpp" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros")
set(sensor_driver_BUILD_EXPORT_DEPENDS "ivcommon" "sensor_driver_msgs" "geometry_msgs" "message_runtime" "nav_msgs" "rosbag" "roscpp" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros")
set(sensor_driver_BUILDTOOL_DEPENDS "catkin")
set(sensor_driver_BUILDTOOL_EXPORT_DEPENDS )
set(sensor_driver_EXEC_DEPENDS "ivcommon" "sensor_driver_msgs" "geometry_msgs" "message_runtime" "nav_msgs" "rosbag" "roscpp" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros")
set(sensor_driver_RUN_DEPENDS "ivcommon" "sensor_driver_msgs" "geometry_msgs" "message_runtime" "nav_msgs" "rosbag" "roscpp" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros")
set(sensor_driver_TEST_DEPENDS )
set(sensor_driver_DOC_DEPENDS )
set(sensor_driver_URL_WEBSITE "")
set(sensor_driver_URL_BUGTRACKER "")
set(sensor_driver_URL_REPOSITORY "")
set(sensor_driver_DEPRECATED "")