// Generated by gencpp from file sensor_driver_msgs/stiffwater.msg
// DO NOT EDIT!


#ifndef SENSOR_DRIVER_MSGS_MESSAGE_STIFFWATER_H
#define SENSOR_DRIVER_MSGS_MESSAGE_STIFFWATER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensor_driver_msgs
{
template <class ContainerAllocator>
struct stiffwater_
{
  typedef stiffwater_<ContainerAllocator> Type;

  stiffwater_()
    : header()
    , ogmheight(0)
    , ogmwidth(0)
    , vehicle_x(0)
    , vehicle_y(0)
    , resolution(0.0)
    , data()  {
    }
  stiffwater_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ogmheight(0)
    , ogmwidth(0)
    , vehicle_x(0)
    , vehicle_y(0)
    , resolution(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _ogmheight_type;
  _ogmheight_type ogmheight;

   typedef int16_t _ogmwidth_type;
  _ogmwidth_type ogmwidth;

   typedef int16_t _vehicle_x_type;
  _vehicle_x_type vehicle_x;

   typedef int16_t _vehicle_y_type;
  _vehicle_y_type vehicle_y;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> const> ConstPtr;

}; // struct stiffwater_

typedef ::sensor_driver_msgs::stiffwater_<std::allocator<void> > stiffwater;

typedef boost::shared_ptr< ::sensor_driver_msgs::stiffwater > stiffwaterPtr;
typedef boost::shared_ptr< ::sensor_driver_msgs::stiffwater const> stiffwaterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_driver_msgs::stiffwater_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_driver_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'sensor_driver_msgs': ['/home/zx/CODE/ws0214/src/sensor_driver/sensor_driver_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88737214cd1e847e12b0a969fb43ebbd";
  }

  static const char* value(const ::sensor_driver_msgs::stiffwater_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88737214cd1e847eULL;
  static const uint64_t static_value2 = 0x12b0a969fb43ebbdULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_driver_msgs/stiffwater";
  }

  static const char* value(const ::sensor_driver_msgs::stiffwater_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
int16 ogmheight\n\
int16 ogmwidth\n\
int16 vehicle_x\n\
int16 vehicle_y\n\
float32 resolution\n\
int16[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sensor_driver_msgs::stiffwater_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ogmheight);
      stream.next(m.ogmwidth);
      stream.next(m.vehicle_x);
      stream.next(m.vehicle_y);
      stream.next(m.resolution);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stiffwater_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_driver_msgs::stiffwater_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_driver_msgs::stiffwater_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ogmheight: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ogmheight);
    s << indent << "ogmwidth: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ogmwidth);
    s << indent << "vehicle_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vehicle_x);
    s << indent << "vehicle_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vehicle_y);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_DRIVER_MSGS_MESSAGE_STIFFWATER_H
