set(_CATKIN_CURRENT_PACKAGE "sub_test")
set(sub_test_VERSION "0.0.0")
set(sub_test_MAINTAINER "zx <zx@todo.todo>")
set(sub_test_PACKAGE_FORMAT "2")
set(sub_test_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(sub_test_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(sub_test_BUILDTOOL_DEPENDS "catkin")
set(sub_test_BUILDTOOL_EXPORT_DEPENDS )
set(sub_test_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(sub_test_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(sub_test_TEST_DEPENDS )
set(sub_test_DOC_DEPENDS )
set(sub_test_URL_WEBSITE "")
set(sub_test_URL_BUGTRACKER "")
set(sub_test_URL_REPOSITORY "")
set(sub_test_DEPRECATED "")