set(_CATKIN_CURRENT_PACKAGE "extractroad")
set(extractroad_VERSION "0.0.0")
set(extractroad_MAINTAINER "Jerry JI <jikaijin94@gmail.com>")
set(extractroad_PACKAGE_FORMAT "2")
set(extractroad_BUILD_DEPENDS "g++-static" "protobuf-dev" "python-sphinx" "message_generation" "ivcommon" "sensor_driver_msgs" "sensor_driver" "stiff" "eigen_conversions" "geometry_msgs" "libgflags-dev" "message_generatioon" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs" "iv_slam_ros_msgs")
set(extractroad_BUILD_EXPORT_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "stiff" "eigen_conversions" "geometry_msgs" "libgflags-dev" "message_generatioon" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs" "iv_slam_ros_msgs")
set(extractroad_BUILDTOOL_DEPENDS "catkin")
set(extractroad_BUILDTOOL_EXPORT_DEPENDS )
set(extractroad_EXEC_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "stiff" "eigen_conversions" "geometry_msgs" "libgflags-dev" "message_generatioon" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs" "iv_slam_ros_msgs")
set(extractroad_RUN_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "stiff" "eigen_conversions" "geometry_msgs" "libgflags-dev" "message_generatioon" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs" "iv_slam_ros_msgs")
set(extractroad_TEST_DEPENDS )
set(extractroad_DOC_DEPENDS )
set(extractroad_URL_WEBSITE "")
set(extractroad_URL_BUGTRACKER "")
set(extractroad_URL_REPOSITORY "")
set(extractroad_DEPRECATED "")