set(_CATKIN_CURRENT_PACKAGE "negative_detection")
set(negative_detection_VERSION "0.0.0")
set(negative_detection_MAINTAINER "Jerry JI <jikaijin94@gmail.com>")
set(negative_detection_PACKAGE_FORMAT "2")
set(negative_detection_BUILD_DEPENDS "g++-static" "protobuf-dev" "python-sphinx" "message_generation" "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(negative_detection_BUILD_EXPORT_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(negative_detection_BUILDTOOL_DEPENDS "catkin")
set(negative_detection_BUILDTOOL_EXPORT_DEPENDS )
set(negative_detection_EXEC_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(negative_detection_RUN_DEPENDS "ivcommon" "sensor_driver_msgs" "sensor_driver" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "message_runtime" "nav_msgs" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(negative_detection_TEST_DEPENDS )
set(negative_detection_DOC_DEPENDS )
set(negative_detection_URL_WEBSITE "")
set(negative_detection_URL_BUGTRACKER "")
set(negative_detection_URL_REPOSITORY "")
set(negative_detection_DEPRECATED "")